### ISSUE TITLE
CUDA error 35 at /home/runner/work/ctransformers/ctransformers/models/ggml/ggml-cuda.cu:5067: CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by thistleknot** [marella/ctransformers#139]
What cuda drivers are needed?

I'm able to run llama-cpp-pyhon and llama.cpp just fine, but not this tool

Ubuntu 22
Cuda 11.7
driver is 515.43.04

**Comment by thistleknot** [comment]
note
works in 12.2
but not 11.7/11.8 :/
too bad soo sad for my 4GB VRAM cards

**Comment by sujeendran** [comment]
@thistleknot - Here is a fix that worked for me: https://github.com/marella/ctransformers/issues/90#issuecomment-1734127938

**Comment by thistleknot** [comment]
Thank you

I got llama.cpp to work on one card that Max's out on compute 5.2 by
setting the compute capability explicitly in the makelist file. I presume
this is similar. However I have yet to test similar changes on this. Will
try sometime this week hopefully

**Comment by alifatmi** [comment]
i also got this error but following commands worked for me.
#Install CUDA libraries using:
pip install ctransformers[cuda]
run above command and run your project code.
